name: baccerelli
favicon: null
layout_spectrum: 0
typography_spectrum: 0.42814
title: digital arts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d4d1c0'
    - '#979797'
    - '#b33124'
    - '#4f7299'
  brandStrength: 0.9375
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
