name: baccerelli
favicon: null
layout_spectrum: 0.22762136394158006
typography_spectrum: 0.3393760188482702
title: digital arts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.92567622452043
  lightness: 0.7057500053197145
  saturation: 0.6642569683026522
  rhythmicContrast: 0.6899539132136852
purpose: []
